# Generated by Django 5.2.1 on 2025-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isFeatured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='isSlider',
            field=models.BooleanField(default=False),
        ),
    ]
